### ISSUE TITLE
Remote GM

### ISSUE THREAD

**Issue by k9lego** [amir-arad/EmptyEpsilon#33]
I'm quite curious, does this have the remote GM you talked about in your merge request with EE? Technically could this support Daid's EE clients as well (presuming its the same "version" or have you made some changes that might break compatibility?

**Comment by amir-arad** [comment]
The EE protocol is implicit, which makes it very fragile: changing even one field in a replicated class is breaking compatibility. that's why the versioning is so strict.

I've made many such changes (added a tractor beam, for one)...

**Comment by k9lego** [comment]
Gotcha! That makes sense. I'm presuming this fork of EE does have the remote GM feature? I've been waiting for months for EE to implement this :)

**Comment by amir-arad** [comment]
yes it does! it also has many other changes. 
If you want only the remote GM feature, you can check out (pun!) daid/EmptyEpsilon#597. I guess once you build one of them you can build the other with no fuss.

**Comment by k9lego** [comment]
I mean, it'd be pretty cool having more of these features! Hopefully Daid will merge all of these someday... One idea I have (and will probably try to implement someday if its not added) is the ability to select objects in GM and lock them from selection. Then a "Unlock All" objects button would be available. This would be useful for locking stations, nebula, etc in place as GM so you don't ruin the experience

**Comment by amir-arad** [comment]
regarding features being merged to main EE, I dunno. 
the changes I make are not always trivial, so they require a lot of time and testing to approve. AFAIK there aren't many of those lately, so we accumulate non-merged features.
and like any debt, they get harder to merge as they progress. for example,  the possess feature relies on two different un-merged features (remote GM, and drones) and is tied to a third (factions control). so I'm not optimistic about it getting merged. furthermore, I would like to combine it with daid/EmptyEpsilon#650 for usability, which will make it even less likely to get merged.

about the lock feature, sounds really nice. the coherence feature (the ability to lock items that the player see) is something I thought back in the day but it always seemed very complicated.

**Comment by k9lego** [comment]
Yeah, those would be nice but I agree it'd be complicated. Any chance you'll make another release with the Hue feature upstream? I love what you've done with the game!
